"""update shifts table time

Revision ID: 2aa9fdd7e53a
Revises: 89d72194f6d0
Create Date: 2023-04-29 14:21:02.884559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa9fdd7e53a'
down_revision = '89d72194f6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
